version: "3.3"

services:

  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: GachiSchool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 24680
    ports:
      - "5432:5432"

  reg-sys:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    image: "${IMAGE_NAME:-regsys}:${IMAGE_VERSION:-latest}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/GachiSchool
    ports:
      - 8080:8080